// forward_city.cpp — PRODUCTION forward airflow + scalar (contaminant) solve on a
// mid-sized city generated by the DENSITY city builder.
//
// This is the live-flow forward dose regime (FORWARD_LIVE.md) — HRR collision +
// linear QUICK scalar, accidental-BURST release run to 99% clearance so the
// cumulative dose Θ=∫C dt is self-terminating — wired onto a real city instead of
// the MUST container array. It closes the gap flagged in exposure_solve.cpp /
// forward_live.cpp ("for a real city swap in city_builder7.h + voxelize.h"):
//
//   1. density city builder  (city_zoning.h generate()+rezone(), dens_enable)  ─┐
//   2. voxelize solid buildings (voxelize.h; parks stay porous)                  │
//   3. source DISTRIBUTION over Ω = every outdoor ground cell (streets + parks) ─┤ ONE run
//      released simultaneously via the per-cell source MASK (linear ⇒ aggregate  │  per
//      dose = Σ per-cell bursts; FORWARD_LIVE.md item 1, now implemented)        │  seed
//   4. HRR mean-flow spin-up (3 flow-throughs) → live QUICK burst transport      │
//   5. J = ⟨w, Θ⟩ / |Ω|  — population dose per unit released mass PER source cell ┘
//
// DATASET PERSISTENCE: every field the visualizer needs is written to OUT_DIR as a
// self-describing binary (5-int header: nx,ny,nz,dx*1000,ncomp) BEFORE any plotting,
// so if the viz suite fails you reload from stored values (meta.txt lists them).
//
// RELAXED COST 732 BUFFERS (this case): the lateral/upwind/downwind margins and the
// vertical headroom are deliberately set BELOW the COST 732 / Franke (2006)
// recommendations for a tighter viz frame and less compute. Good for a quick-look /
// visualization; NOT a publication-grade solve — the banner says so.
//
// The city grid resolution is the COMPILE-TIME constant CELL_SIZE_M in
// city_builder7.h — build with -DCELL_SIZE_M=2.0 for the coarse 2 m production run.
//
// Build (CPU/OpenMP):
//   g++ -O3 -std=c++17 -fopenmp -DCELL_SIZE_M=2.0 -c lbm_kernels_cpu.cpp -o kc.o
//   g++ -O3 -std=c++17 -fopenmp -DCELL_SIZE_M=2.0 -c lbm_solver.cpp      -o so.o
//   g++ -O3 -std=c++17 -fopenmp -DCELL_SIZE_M=2.0 forward_city.cpp kc.o so.o -o forward_city
// Run:  COLL=hrr SCALAR=quick ./forward_city         (all knobs via env, see below)
//   DUMP_GEOM_ONLY=1 → build+store geometry/plan rasters and exit (for the domain image).
//
// GPU: the QUICK scalar (mode 3) and the source mask are CPU-only for now.
#include "lbm_solver.h"
#include "city_zoning.h"   // density builder: Params, MixedZoningParams, generate, rezone, export_city
#include "voxelize.h"      // city → LBM voxel grid (types, perm, dep_vel, inh)
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <cmath>
#include <string>
#include <algorithm>
#include <functional>   // host-only (this .cpp is never compiled by nvcc)

using namespace city;

static double envd(const char* k, double d){ const char* e=getenv(k); return e? atof(e):d; }
static int    envi(const char* k, int    d){ const char* e=getenv(k); return e? atoi(e):d; }

int main(){
    // Line-buffer stdout/stderr so `tail -f` shows live progress even when the run
    // is detached and output is redirected to a file (libc would otherwise switch
    // to 4 KB block buffering and the log would look empty for long stretches).
    setvbuf(stdout, nullptr, _IOLBF, 0);
    setvbuf(stderr, nullptr, _IOLBF, 0);

    std::string OUT = getenv("OUT_DIR") ? getenv("OUT_DIR") : "forward_city_out";
    { std::string c="mkdir -p '"+OUT+"'"; if(system(c.c_str())){} }
    auto status = [&](const char* s){ FILE* f=fopen((OUT+"/STATUS").c_str(),"w"); if(f){fprintf(f,"%s\n",s);fclose(f);} };
    status("RUNNING");

    // ── city morphology (density builder) — mid-sized defaults; override via env ──
    const double CITY_M = envd("CITY_M", 600.0);    // square city extent (m)
    const double POP    = envd("POP",   20000.0);   // total population

    // ── COST 732 buffers RELAXED FOR THIS CASE (tighter frame + less compute). ──
    // Named for the default 0° (+x) wind: upwind=−x, downwind=+x, lateral=±y.
    // COST 732 / Franke 2006 would want ~5H upwind/lateral/top and ~15H downwind;
    // these are well below that on purpose (visualization / quick-look, not
    // publication). Restore with BUF_UP/BUF_DOWN/BUF_LAT/HEADROOM_H env.
    const double BUF_UP    = envd("BUF_UP",    40.0);   // upwind fetch (m)  (enlarged from 15)
    const double BUF_DOWN  = envd("BUF_DOWN",  70.0);   // downwind wake (m) (enlarged from 30)
    const double BUF_LAT   = envd("BUF_LAT",   35.0);   // lateral (m)       (enlarged from 15)
    const double HEADROOM_H = envd("HEADROOM_H", 3.0);  // top headroom as ×(tallest building) (was 2)

    Params p{};
    p.city_w = CITY_M; p.city_h = CITY_M;
    p.population_total = POP;
    p.wind_direction = 0.0;
    p.base_height    = BASE_HEIGHT_M;
    p.block_w   = envd("BLOCK_W", 60.0);
    p.block_d   = envd("BLOCK_D", 60.0);
    p.roughness = envd("ROUGH",    0.5);
    p.road_w_x  = p.road_w_y = envd("STREET_W", 20.0);
    p.park_fraction = envd("PARK_FRAC", 0.15);
    p.cbd_peak = 40.0; p.cbd_decay = 8e-6; p.patchiness = 0.0;   // unused by dens model, sane for layout pass
    p.cbd_aspect=1; p.cbd_angle=0; p.biz_inner_frac=0; p.biz_aspect=1;
    p.park_centrality = 0.5;
    p.buf_xn = BUF_UP; p.buf_xp = BUF_DOWN; p.buf_yn = p.buf_yp = BUF_LAT;
    p.Sx = p.buf_xn + p.city_w + p.buf_xp;
    p.Sy = p.buf_yn + p.city_h + p.buf_yp;
    double dom_cx = p.buf_xn + p.city_w*0.5, dom_cy = p.buf_yn + p.city_h*0.5;
    p.cbd_x=dom_cx; p.cbd_y=dom_cy; p.biz_center_x=dom_cx; p.biz_center_y=dom_cy;
    p.source_x=p.buf_xn-10; p.source_y=dom_cy;

    MixedZoningParams mzp{};
    mzp.dens_enable       = true;
    mzp.peak_height       = envd("PEAK_H",         45.0);   // tallest building (m); mid-rise
    // Polycentric business: 3 employment centres on a ring (emp_centrality<1 pushes
    // them off-centre) so business no longer clusters only in the middle.
    mzp.emp_centers       = envi("EMP_CENTERS",     3);
    mzp.emp_centrality    = envd("EMP_CTR",         0.55);
    mzp.emp_concentration = envd("EMP_CONC",        0.5);
    mzp.res_gradient      = envd("RES_GRAD",        1.0);
    mzp.jh_mix            = envd("JH_MIX",          0.5);
    mzp.biz_scatter  = 0.0; mzp.park_scatter = 0.0;

    printf("[forward_city] density city: %.0fx%.0f m, pop=%.0f, dx=%.2f m\n", CITY_M, CITY_M, POP, (double)CELL);
    printf("[forward_city] RELAXED buffers (this case): upwind=%.0f downwind=%.0f lateral=%.0f m, headroom=%.1fxH  (below COST 732)\n",
           BUF_UP, BUF_DOWN, BUF_LAT, HEADROOM_H);
    Result r0 = generate(p);
    Result r  = rezone(p, r0, mzp);
    std::string cityfile = OUT + "/city_density.txt";
    export_city(cityfile.c_str(), p, r);
    printf("[forward_city] city: blocks=%d biz=%d maxH=%.0fm pop=%.0f inhab=%.0f -> %s\n",
           r.num_blocks, r.counts[1], r.max_height, r.population, r.total_inhabitance, cityfile.c_str());

    // ── voxelize with SOLID buildings; RELAXED vertical headroom via nz_fixed ─────
    int maxHC=0; for(auto& b: r.blocks) maxHC=std::max(maxHC, b.height_cells);
    int nz_relaxed = std::max(4, maxHC + (int)std::ceil(HEADROOM_H*(double)maxHC) + 1);
    int nz_cost    = nz_cost732((double)maxHC * CELL);
    printf("[forward_city] vertical: tallest=%d cells; nz(relaxed)=%d vs nz(COST 732)=%d  (%.0f%% fewer z-planes)\n",
           maxHC, nz_relaxed, nz_cost, 100.0*(1.0-(double)nz_relaxed/std::max(1,nz_cost)));
    VoxelGrid g = voxelize(p, r, /*solid_buildings=*/true, -1.0, 1800.0, 0.5, /*nz_fixed=*/nz_relaxed);
    print_voxel_summary(g);
    const int nx=g.nx, ny=g.ny, nz=g.nz; const size_t N=(size_t)nx*ny*nz;
    const double dx = g.cell_size;
    auto IDX=[&](int x,int y,int z){ return (size_t)z*ny*nx + (size_t)y*nx + x; };

    // ── self-describing binary writers (5-int header: nx,ny,nz,dx*1000,ncomp) ────
    auto hdr5=[&](FILE* f,int nc){ int h[5]={nx,ny,nz,(int)std::lround(dx*1000.0),nc}; fwrite(h,sizeof(int),5,f); };
    auto wrf=[&](const std::string& fn,const float* d,size_t n,int nc){
        FILE* f=fopen((OUT+"/"+fn).c_str(),"wb"); if(!f){fprintf(stderr,"[forward_city] WARN cannot write %s\n",fn.c_str());return;}
        hdr5(f,nc); fwrite(d,sizeof(float),n,f); fclose(f);
        printf("[forward_city]   stored %s (%zu floats, ncomp=%d)\n",fn.c_str(),n,nc); };
    auto wru=[&](const std::string& fn,const uint8_t* d,size_t n){
        FILE* f=fopen((OUT+"/"+fn).c_str(),"wb"); if(!f){fprintf(stderr,"[forward_city] WARN cannot write %s\n",fn.c_str());return;}
        hdr5(f,1); fwrite(d,1,n,f); fclose(f);
        printf("[forward_city]   stored %s (%zu bytes)\n",fn.c_str(),n); };

    // geometry dataset (compact: cell type only) — needed to mask solids in viz
    wru("geom_type.u8", g.type.data(), N);

    // ── plan-view rasters for the domain image (buffer/street/park/usage + height) ─
    // codes: 0=buffer(outside city) 1=street(inside city) 2=park 3=business 4=res_high 5=res_low
    std::vector<uint8_t> plan(N/nz>0? (size_t)nx*ny:0, 0);
    plan.assign((size_t)nx*ny, 0);
    std::vector<float> planh((size_t)nx*ny, 0.f);
    int cxn=(int)std::llround(p.buf_xn/dx), cxp=nx-(int)std::llround(p.buf_xp/dx);
    int cyn=(int)std::llround(p.buf_yn/dx), cyp=ny-(int)std::llround(p.buf_yp/dx);
    for(int y=0;y<ny;++y)for(int x=0;x<nx;++x)
        if(x>=cxn&&x<cxp&&y>=cyn&&y<cyp) plan[(size_t)y*nx+x]=1;   // street (open, inside city)
    for(auto& b: r.blocks){
        uint8_t code = (b.usage==PARK)?2 : (b.usage==BUSINESS)?3 : (b.usage==RES_HIGH)?4 : 5;
        for(int y=std::max(0,b.y0);y<std::min(ny,b.y1);++y)
          for(int x=std::max(0,b.x0);x<std::min(nx,b.x1);++x){
              plan[(size_t)y*nx+x]=code; planh[(size_t)y*nx+x]=(float)(b.height_cells*dx); }
    }
    { FILE* f=fopen((OUT+"/plan_code.u8").c_str(),"wb"); if(f){int h[5]={nx,ny,1,(int)std::lround(dx*1000.0),1};fwrite(h,sizeof(int),5,f);fwrite(plan.data(),1,plan.size(),f);fclose(f);} }
    { FILE* f=fopen((OUT+"/plan_height.f32").c_str(),"wb"); if(f){int h[5]={nx,ny,1,(int)std::lround(dx*1000.0),1};fwrite(h,sizeof(int),5,f);fwrite(planh.data(),sizeof(float),planh.size(),f);fclose(f);} }

    // meta (human + machine readable): everything needed to reload the binaries
    auto write_meta=[&](double Jmean,double Jstd,int nEns,long nOmega,double dep,double air,double outfl,double emit,bool done){
        FILE* f=fopen((OUT+"/meta.txt").c_str(),"w"); if(!f) return;
        fprintf(f,"# forward_city dataset — self-describing run metadata\n");
        fprintf(f,"grid_nx %d\ngrid_ny %d\ngrid_nz %d\ndx_m %.4f\n",nx,ny,nz,dx);
        fprintf(f,"city_w_m %.1f\ncity_h_m %.1f\n",CITY_M,CITY_M);
        fprintf(f,"buf_upwind_m %.1f\nbuf_downwind_m %.1f\nbuf_lateral_m %.1f\nheadroom_xH %.2f\n",BUF_UP,BUF_DOWN,BUF_LAT,HEADROOM_H);
        fprintf(f,"nz_relaxed %d\nnz_cost732 %d\n",nz_relaxed,nz_cost);
        fprintf(f,"city_origin_cells %d %d\ncity_extent_cells %d %d\n",cxn,cyn,cxp,cyp);
        fprintf(f,"wind_deg %.1f\nU_inlet_ms %.3f\n",envd("WIND_DEG",0.0),envd("U_INLET",4.0));
        fprintf(f,"blocks %d\nmaxH_m %.1f\npopulation %.0f\ninhabitance %.0f\n",r.num_blocks,r.max_height,r.population,r.total_inhabitance);
        fprintf(f,"omega_source_cells %ld\n",nOmega);
        fprintf(f,"# binary layout: each .f32/.u8 starts with 5 int32 [nx,ny,nz,dx*1000,ncomp]\n");
        fprintf(f,"# fields: geom_type.u8(0=fluid,1=ground,2=shell,3=indoor) receptor_w.f32 source_mask.u8\n");
        fprintf(f,"#         umean_full.f32(ncomp=4: ux,uy,uz,nut planar) theta_last.f32 theta_mean.f32\n");
        fprintf(f,"#         plan_code.u8(nz=1) plan_height.f32(nz=1) tiac_zped.bin vel_zped.bin\n");
        if(done){
          fprintf(f,"status COMPLETE\nJ_mean %.6e\nJ_std %.6e\nN_ens %d\n",Jmean,Jstd,nEns);
          fprintf(f,"mass_emitted %.6e\nmass_deposited %.6e\nmass_airborne %.6e\nmass_outflow %.6e\n",emit,dep,air,outfl);
        } else fprintf(f,"status GEOMETRY_ONLY\n");
        fclose(f);
    };

    // ── source distribution Ω: outdoor GROUND-level cells (z=1) — streets + parks ──
    std::vector<uint8_t> srcmask(N, 0);
    long nOmega=0; const int zsrc=1;
    for(int y=0;y<ny;++y)for(int x=0;x<nx;++x){
        size_t id=IDX(x,y,zsrc); uint8_t t=g.type[id];
        bool open=(t==CELL_FLUID), parkg=(t==CELL_SHELL && g.perm[id]>0.5f);
        if(open||parkg){ srcmask[id]=1; ++nOmega; }
    }
    if(nOmega<=0){ status("FAIL_EMPTY_OMEGA"); fprintf(stderr,"[forward_city] FATAL: empty source set Ω\n"); return 2; }
    wru("source_mask.u8", srcmask.data(), N);
    printf("[forward_city] source Ω = %ld ground cells (streets + parks), released simultaneously\n", nOmega);

    // ── receptor w: F_inf infiltration, weighted by per-building eff_inh ──────────
    const double z_ped = envd("Z_PED", 2.0);
    float FINF=(float)envd("FINF",0.62), F_IN=(float)envd("F_IN",0.87), F_OUT=(float)envd("F_OUT",0.075);
    if(FINF>1.f) FINF=1.f;
    const bool FLAT_W = envi("FLAT_W",0)!=0;
    const int zped = std::min(nz-1, std::max(1,(int)std::llround(z_ped/dx)));  // clamp: valid slice index
    std::vector<float> w(N,0.f); std::vector<int> stamp(N,-1);
    double wEnv=0; long nEnvTot=0; int bxmin=nx,bxmax=-1,bymin=ny,bymax=-1;
    for(int bi=0;bi<(int)r.blocks.size();++bi){
        const Block& b=r.blocks[bi];
        if(b.usage==PARK) continue; int hc=b.height_cells; if(hc<1) continue;
        int x0=std::max(0,b.x0),x1=std::min(nx,b.x1),y0=std::max(0,b.y0),y1=std::min(ny,b.y1);
        if(x1<=x0||y1<=y0) continue; int hz=std::min(hc,nz-1);
        bxmin=std::min(bxmin,x0);bxmax=std::max(bxmax,x1-1);bymin=std::min(bymin,y0);bymax=std::max(bymax,y1-1);
        if(b.eff_inh<=0.0) continue;
        std::vector<size_t> env; const int dxn[6]={1,-1,0,0,0,0},dyn[6]={0,0,1,-1,0,0},dzn[6]={0,0,0,0,1,-1};
        for(int z=1;z<=hz;++z)for(int y=y0;y<y1;++y)for(int x=x0;x<x1;++x){
            size_t sid=IDX(x,y,z); if(g.type[sid]!=CELL_SHELL) continue;
            for(int d=0;d<6;++d){ int xx=x+dxn[d],yy=y+dyn[d],zz=z+dzn[d];
                if(xx<0||xx>=nx||yy<0||yy>=ny||zz<1||zz>=nz) continue;
                size_t nid=IDX(xx,yy,zz); if(g.type[nid]!=CELL_FLUID) continue;
                if(stamp[nid]==bi) continue; stamp[nid]=bi; env.push_back(nid); } }
        if(env.empty()) continue;
        double per=(double)F_IN*FINF*(FLAT_W?1.0:b.eff_inh)/(double)env.size();
        for(size_t nid:env){ w[nid]+=(float)per; wEnv+=per; ++nEnvTot; }
    }
    double wPed=0; long nPed=0;
    if(bxmax>=bxmin){ int mg=std::max(2,(int)std::llround(10.0/dx));
        int px0=std::max(1,bxmin-mg),px1=std::min(nx-2,bxmax+mg),py0=std::max(1,bymin-mg),py1=std::min(ny-2,bymax+mg);
        int z=std::min(zped,nz-2);
        for(int y=py0;y<=py1;++y)for(int x=px0;x<=px1;++x){ size_t id=IDX(x,y,z);
            if(g.type[id]==CELL_FLUID){ w[id]+=F_OUT; wPed+=F_OUT; ++nPed; } } }
    double wsum=wEnv+wPed;
    printf("[forward_city] receptor w (%s F_inf=%.2f f_in=%.2f f_out=%.3f): indoor %ld cells (w=%.4g) + outdoor %ld cells (w=%.4g)\n",
           FLAT_W?"UNIFORM":"eff_inh-weighted",FINF,F_IN,F_OUT,nEnvTot,wEnv,nPed,wPed);
    if(wsum<=0){ status("FAIL_EMPTY_RECEPTOR"); fprintf(stderr,"[forward_city] FATAL: empty receptor field\n"); return 2; }
    wrf("receptor_w.f32", w.data(), N, 1);

    // Geometry-only mode: everything the domain image needs is stored; stop here.
    if(envi("DUMP_GEOM_ONLY",0)){
        write_meta(0,0,0,nOmega,0,0,0,0,false);
        status("GEOMETRY_ONLY");
        printf("[forward_city] DUMP_GEOM_ONLY: geometry + plan rasters stored in %s — exiting before LBM.\n",OUT.c_str());
        return 0;
    }

    // ── run controls + viz snapshot configuration ───────────────────────────
    const int   N_ENS   = std::max(1, envi("N_ENS",1));
    const float U_INLET = (float)envd("U_INLET",4.0);
    const float WIND    = (float)(envd("WIND_DEG",0.0)*M_PI/180.0);
    const int   MAXSTEP = envi("MAX_STEPS",300000);
    const int   SPINFT  = envi("SPINUP_FT",3);
    const float CLEAR   = (float)envd("CLEAR_FRAC",0.01);
    const int   MAXW    = envi("MAX_WARMUP",80000);
    const bool  STORE_FULL = envi("STORE_FULL",1)!=0;
    const int   SNAP_EVERY = envi("SNAP_EVERY",500);    // Phase-B steps between viz snapshots (0=off)
    const double C3D_TIME_S= envd("C3D_TIME_S",30.0);   // grab the full-3D concentration once past this

    // Config factory — the SAME operating point for the pre-flight and every member.
    auto make_cfg=[&](unsigned seed,int snap)->lbm::Config{
        lbm::Config c{};
        c.nx=nx; c.ny=ny; c.nz=nz; c.cell_size=(float)dx;
        c.U_inlet=U_INLET; c.wind_angle=WIND;
        c.nu_phys=1.5e-5f; c.Cw=0.325f; c.Sc_t=0.7f; c.D_mol=1e-5f;
        c.collision_mode=2; c.hrr_sigma=0.98f; c.scalar_advection=3;
        c.source_x=0; c.source_y=0; c.source_z=(float)dx; c.Q_source=1.0f;
        c.burst_release=true; c.clearance_frac=CLEAR; c.abl_seed=seed;
        c.particle_diam=0.f; c.particle_density=1000.f;
        c.max_steps=MAXSTEP; c.check_interval=500; c.conv_threshold=1e-4f;
        c.max_warmup=MAXW; c.avg_threshold=2e-3f; c.avg_steps=0; c.spinup_steps=0;
        c.spinup_ft=SPINFT; c.release_time=0.f; c.snapshot_every=snap;
        c.inlet_profile=1; c.abl_z0=0.045f; c.abl_zref=4.0f;
        c.abl_Lturb=20.f; c.abl_nmodes=100; c.abl_sigu_ratio=2.5f; c.abl_sigv_ratio=1.9f; c.abl_sigw_ratio=1.25f;
        return c;
    };

    // ── PREFLIGHT: verify every parameter is correct, then EXIT before running ──
    if(envi("PREFLIGHT",0)){
        printf("\n[preflight] ===== parameter, stability & memory pre-flight (NO LBM run) =====\n");
        double Ma=0.1, u_lb=Ma/std::sqrt(3.0);
        double dt=u_lb*dx/(double)U_INLET, nu_lb=1.5e-5*dt/(dx*dx), tau_f=3.0*nu_lb+0.5, D_lb=1e-5*dt/(dx*dx);
        printf("[preflight] grid %dx%dx%d = %.2fM cells; dx=%.2f m; U=%.2f m/s; wind=%.0f deg\n",nx,ny,nz,N/1e6,dx,U_INLET,envd("WIND_DEG",0.0));
        printf("[preflight] dt=%.4g s/step; u_lb=%.4g (Ma=%.2f); nu_lb=%.3g tau_f=%.4f; D_lb=%.3g\n",dt,u_lb,Ma,nu_lb,tau_f,D_lb);
        printf("[preflight] buffers up/down/lat=%.0f/%.0f/%.0f m headroom=%.1fxH; nz relaxed=%d vs COST 732=%d\n",BUF_UP,BUF_DOWN,BUF_LAT,HEADROOM_H,nz,nz_cost);
        printf("[preflight] Omega=%ld src cells; receptor wsum=%.4g; snapshot_every=%d; C3D at %.1fs; cap=%d steps\n",nOmega,wsum,SNAP_EVERY,C3D_TIME_S,MAXSTEP);
        bool ok=true; auto need=[&](bool c,const char* m){ printf("[preflight]   [%s] %s\n",c?"PASS":"FAIL",m); if(!c) ok=false; };
        need(nx>4&&ny>4&&nz>4,"grid dimensions sane (>4 each)");
        need(nOmega>0,"source set Omega non-empty");
        need(wsum>0,"receptor field non-empty");
        need(std::isfinite(dt)&&dt>0,"physical timestep dt finite and positive");
        need(tau_f>0.5,"flow relaxation tau_f > 0.5 (positive effective viscosity)");
        need(Ma<0.3,"inlet Mach < 0.3 (low-compressibility regime)");
        need(SNAP_EVERY>=0,"snapshot interval non-negative");
        need((double)N*13.0/1e9 < 24.0,"host memory estimate < 24 GB (adjust if your box differs)");
        printf("[preflight] constructing solver (runs the ctor memory pre-flight + resolves the operator)...\n");
        lbm::Solver s(make_cfg(1000u,0));
        int got=s.effective_collision(), scal=s.effective_scalar();
        need((got==2&&scal==3)||getenv("COLLISION")||getenv("SCALAR"),"effective operator = HRR + QUICK");
        if(ok){ status("PREFLIGHT_OK"); printf("\n[preflight] ===== ALL PARAMETERS CORRECT — cleared to run =====\n"); return 0; }
        status("PREFLIGHT_FAIL"); fprintf(stderr,"\n[preflight] ===== PARAMETER CHECK FAILED — REFUSING to run =====\n"); return 4;
    }

    printf("[forward_city] ensemble N=%d U=%.2f m/s wind=%.0f deg cap=%d steps spinup=%d FT snap_every=%d\n",
           N_ENS,U_INLET,envd("WIND_DEG",0.0),MAXSTEP,SPINFT,SNAP_EVERY);

    // viz snapshot state (used only for the snapshot-enabled member)
    std::string FRAMES=OUT+"/frames"; { std::string cm="mkdir -p '"+FRAMES+"'"; if(system(cm.c_str())){} }
    std::vector<float> Cf,Thf,Depf; long frame_i=0; bool c3d_saved=false; FILE* tsf=nullptr;
    // The callable lives here (host-only std::function); the solver stores only a
    // POD function-pointer to a captureless trampoline over it (nvcc never sees this).
    std::function<void(int,int,int,bool,bool)> snap_fn;

    std::vector<uint8_t> tp=g.type;
    std::vector<double> J(N_ENS,0.0);
    std::vector<float> Theta_sum(N,0.f), tiac, umx,umy,umz,unut;
    double last_dep=0,last_air=0,last_out=0,last_emit=0;
    for(int k=0;k<N_ENS;++k){
        bool snapmem=(k==N_ENS-1 && SNAP_EVERY>0);   // snapshot only the last (single) run
        lbm::Config c=make_cfg(1000u+137u*(unsigned)k, snapmem?SNAP_EVERY:0);
        printf("\n[forward_city] === member %d/%d (seed=%u)%s ===\n",k+1,N_ENS,c.abl_seed,snapmem?" [snapshots ON]":"");
        lbm::Solver s(c);
        if(k==0){ const char* NM[3]={"MRT","reg","HRR"}; int got=s.effective_collision();
            printf("[forward_city] effective collision=%s scalar=%d (wanted HRR+QUICK)\n",NM[got&3],s.effective_scalar());
            if((got!=2||s.effective_scalar()!=3)&&!getenv("COLLISION")&&!getenv("SCALAR")){
                status("FAIL_OPERATOR"); fprintf(stderr,"[forward_city] FATAL: operator mismatch (wanted HRR+QUICK)\n"); return 3; } }
        s.load_geometry(tp.data(),g.perm.data(),g.inh.data(),g.dep_vel.data());
        s.load_source_mask(srcmask.data());

        if(snapmem){   // register the time-resolved viz snapshot hook
            double dt_phys=(double)s.velocity_phys_to_lattice()*dx;
            tsf=fopen((OUT+"/exposure_timeseries.csv").c_str(),"w");
            if(tsf) fprintf(tsf,"frame,phaseB_step,t_s,exposure_rate,cumulative_dose,airborne_mass,deposited_mass,is_release,is_end\n");
            snap_fn = [&,dt_phys](int bstep,int gstep,int scalbuf,bool rel,bool end){
                s.copy_scalar_to_host(Cf,scalbuf); s.copy_tiac_to_host(Thf); s.copy_deposition_to_host(Depf);
                double erate=0,cum=0,airb=0,dep=0;
                for(size_t i=0;i<N;++i){ erate+=(double)w[i]*Cf[i]; cum+=(double)w[i]*Thf[i]; airb+=Cf[i]; dep+=Depf[i]; }
                double trel=bstep*dt_phys;
                // Immediate divergence signal: a non-finite field mid-Phase-B is
                // reported at once (STATUS + loud line) rather than only after run().
                if(!std::isfinite(erate)||!std::isfinite(cum)||!std::isfinite(airb)){
                    status("DIVERGED");
                    fprintf(stderr,"[forward_city] *** FATAL: non-finite concentration at snapshot %ld (t=%.1fs) — SOLUTION DIVERGED ***\n",frame_i,trel);
                }
                char idx[16]; snprintf(idx,sizeof idx,"%04ld",frame_i);
                auto wslice=[&](const std::string& fn,const std::vector<float>& F){
                    FILE* f=fopen((FRAMES+"/"+fn).c_str(),"wb"); if(!f)return; int h[2]={nx,ny};
                    fwrite(h,sizeof(int),2,f); fwrite(&F[(size_t)zped*nx*ny],sizeof(float),(size_t)nx*ny,f); fclose(f); };
                wslice(std::string("conc_")+idx+".f32",Cf);          // ground concentration frame
                wslice(std::string("dep_") +idx+".f32",Depf);        // ground deposition frame
                s.export_velocity((FRAMES+"/vel_"+std::string(idx)+".bin").c_str(),zped);  // instantaneous ground wind
                if(tsf){ fprintf(tsf,"%ld,%d,%.4f,%.6e,%.6e,%.6e,%.6e,%d,%d\n",frame_i,bstep,trel,erate,cum,airb,dep,rel?1:0,end?1:0); fflush(tsf); }
                if(!c3d_saved && (trel>=C3D_TIME_S || end)){        // one full-3D concentration cloud
                    FILE* f=fopen((OUT+"/conc3d_mid.f32").c_str(),"wb");
                    if(f){ int h[5]={nx,ny,nz,(int)std::lround(dx*1000.0),1}; fwrite(h,sizeof(int),5,f); fwrite(Cf.data(),sizeof(float),N,f); fclose(f);
                           printf("[forward_city]   full-3D concentration saved at t=%.1fs -> conc3d_mid.f32\n",trel); }
                    c3d_saved=true;
                }
                printf("[forward_city]   snapshot %ld: t=%.1fs exp_rate=%.3e cumulative=%.3e airborne=%.3e\n",frame_i,trel,erate,cum,airb);
                frame_i++;
            };
            s.set_snapshot_callback(                       // wrap the lambda behind the POD ABI
                [](void* ctx,int a,int b,int c,bool d,bool e){
                    (*static_cast<std::function<void(int,int,int,bool,bool)>*>(ctx))(a,b,c,d,e); },
                &snap_fn);
        }
        lbm::Result res=s.run();

        // ── DIVERGENCE GUARD: fail loudly + immediately on any non-finite state ──
        double Jk=0.0; bool bad = !std::isfinite(res.max_velocity) || !std::isfinite(res.max_concentration);
        if(!bad){ s.copy_tiac_to_host(tiac);
            for(size_t i=0;i<N;++i){ float t=tiac[i]; if(!std::isfinite(t)){ bad=true; break; } Jk+=(double)w[i]*t; } }
        if(bad){
            status("DIVERGED");
            fprintf(stderr,
              "\n**************************************************************\n"
                "*** FATAL: SOLUTION DIVERGED — non-finite values detected  ***\n"
                "***   member %d/%d  max|u|=%g  maxC=%g                      \n"
                "***   run ABORTED; no valid dose. Coarsen dx / lower U /    ***\n"
                "***   raise HRR_SIGMA, or relax CFL, then retry.           ***\n"
                "**************************************************************\n",
              k+1,N_ENS,(double)res.max_velocity,(double)res.max_concentration);
            return 2;
        }
        for(size_t i=0;i<N;++i) Theta_sum[i]+=tiac[i];
        Jk/=(double)nOmega; J[k]=Jk;
        last_dep=res.total_deposited; last_air=res.total_airborne; last_emit=res.total_emitted;
        last_out=res.total_emitted-res.total_deposited-res.total_airborne;
        printf("[forward_city]   member J=%.6e (deposited %.1f%%, airborne %.1f%%)\n",
               Jk,100.0*res.total_deposited/std::max(1e-30,res.total_emitted),
               100.0*res.total_airborne/std::max(1e-30,res.total_emitted));

        if(k==N_ENS-1){   // store the last realisation's fields for the viz suite
            s.export_tiac((OUT+"/tiac_zped.bin").c_str(), zped);
            s.export_avg_velocity((OUT+"/vel_zped.bin").c_str(), zped);
            // umean_full is REQUIRED for the 3D-airflow figure, so it is always
            // stored (independent of STORE_FULL). STORE_FULL only gates the extra
            // Θ fields the core viz suite does not itself consume.
            s.copy_mean_flow_to_host(umx,umy,umz,unut);
            std::vector<float> uf(4*N);
            std::copy(umx.begin(),umx.end(),uf.begin());
            std::copy(umy.begin(),umy.end(),uf.begin()+N);
            std::copy(umz.begin(),umz.end(),uf.begin()+2*N);
            std::copy(unut.begin(),unut.end(),uf.begin()+3*N);
            wrf("umean_full.f32", uf.data(), 4*N, 4);
            if(STORE_FULL) wrf("theta_last.f32", tiac.data(), N, 1);
        }
    }
    if(tsf){ fclose(tsf); tsf=nullptr; }
    double mean=0; for(double v:J) mean+=v; mean/=N_ENS;
    double var=0;  for(double v:J) var+=(v-mean)*(v-mean); double sd=(N_ENS>1)?std::sqrt(var/(N_ENS-1)):0.0;
    if(STORE_FULL){ std::vector<float> tm(N); for(size_t i=0;i<N;++i) tm[i]=Theta_sum[i]/(float)N_ENS; wrf("theta_mean.f32",tm.data(),N,1); }
    write_meta(mean,sd,N_ENS,nOmega,last_dep,last_air,last_out,last_emit,true);
    status("COMPLETE");

    printf("\n[forward_city] ===== city population dose (N=%d realisation%s over Ω=%ld) =====\n",N_ENS,N_ENS>1?"s":"",nOmega);
    printf("  mean J = %.6e   (population dose per unit released mass, per source cell; lattice units)\n",mean);
    if(N_ENS>1) printf("  std  J = %.6e  (%.1f%% of mean)\n",sd,100.0*sd/std::max(1e-30,mean));
    printf("  LOWER is better; compare J ACROSS designs, not in absolute terms.\n");
    printf("  all datasets stored in %s/  (meta.txt describes every binary)\n",OUT.c_str());
    if(frame_i>0) printf("  time-resolved: %ld frames in %s/frames/ + exposure_timeseries.csv + conc3d_mid.f32\n",frame_i,OUT.c_str());
    return 0;
}
